name: Go CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.3" # Specify your Go version here

      - name: Run tests
        run: go test ./... -v -race

  format-check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go tools
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check format
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted. Please run 'go fmt ./...' locally and commit changes."
            exit 1
          fi
